In [1]:
import pandas as pd 
import numpy as np 

In [8]:
#1. How likely is it that you roll doubles when rolling two dice?
outcomes = [1,2,3,4,5,6]

n_simulations = 10000
n_trials = 2

rolls = np.random.choice(outcomes, size=(n_simulations,n_trials))
rolls

array([[6, 6],
       [4, 6],
       [3, 4],
       ...,
       [5, 4],
       [4, 4],
       [2, 6]])

In [49]:
def is_equal(array):
    new_list = []
    for i in range(len(array)):
        new_list.append(array[i][0] == array[i][1])
    return pd.Series(new_list)

In [50]:
doubles = is_equal(rolls)
doubles

0        True
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [51]:
doubles.mean()

0.1639

In [57]:
#2. If you flip 8 coins, what is the probability of getting exactly 3 heads?
coin_outcomes = [0,1]
n_simulations = 10000
n_trials = 8

flips = np.random.choice(coin_outcomes, size=(n_simulations,n_trials))
flips

array([[1, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 0, 1]])

In [58]:
sum_of_flips = flips.sum(axis=1)
sum_of_flips

array([2, 3, 3, ..., 6, 8, 4])

In [60]:
(sum_of_flips == 3).mean()

0.2138

In [61]:
# - What is the probability of getting more than 3 heads?
(sum_of_flips > 3).mean()

0.6393

In [62]:
#3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?
# 1 = data science
billboard_outcomes = [1,0]
n_trials = 2

billboard_flips = np.random.choice(billboard_outcomes,size=(n_simulations,n_trials), p=[0.25,0.75])
billboard_flips

array([[0, 0],
       [0, 0],
       [1, 1],
       ...,
       [0, 0],
       [0, 1],
       [0, 0]])

In [63]:
sum_of_billboard_flips = billboard_flips.sum(axis=1)
sum_of_billboard_flips

array([0, 0, 2, ..., 0, 1, 0])

In [64]:
(sum_of_billboard_flips == 2).mean()

0.065

In [69]:
#4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on Friday afternoon?

pop_tarts = np.random.normal(3,1.5,size=(n_simulations, 5))
pop_tarts

array([[2.05113458, 4.44562965, 2.63832698, 3.44348848, 3.12739122],
       [2.75652257, 3.59668709, 4.92605516, 1.65978575, 3.97959029],
       [2.52029225, 3.15930641, 1.64054788, 4.26377989, 3.68814628],
       ...,
       [3.29549825, 2.15401758, 0.76857705, 5.95136067, 4.38344551],
       [1.60788162, 4.45364102, 2.82428612, 0.61758198, 3.12647435],
       [1.84106256, 4.33749616, 1.09311422, 3.44804375, 3.43159626]])

In [70]:
pop_tarts_sum = pop_tarts.sum(axis=1)
pop_tarts_sum

array([15.70597091, 16.91864085, 15.2720727 , ..., 16.55289907,
       12.62986509, 14.15131295])

In [71]:
(pop_tarts_sum < 17).mean()

0.7203

In [75]:
#5 Compare Heights
# - Men have an average height of 178 cm and standard deviation of 8cm.
# - Women have a mean of 170, sd = 6cm.
# - If a man and woman are chosen at random, P(woman taller than man)?

men = np.random.normal(178,8,size=(n_simulations,1))
women = np.random.normal(170,6,size=(n_simulations,1))
women

array([[175.71325164],
       [172.10146709],
       [169.15354303],
       ...,
       [167.42292296],
       [159.29505261],
       [166.31375139]])

In [77]:
(women > men).mean()

0.2158

In [80]:
#6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download 
# is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, 
# no one has an installation issue? 100 students?
corrupt_outcomes = [1,0]

installations = np.random.choice(corrupt_outcomes,size=(n_simulations,50),p=[0.004,0.996])
installations

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [82]:
(installations.sum(axis=1) == 0).mean()

0.8197

In [84]:
installations_100 = np.random.choice(corrupt_outcomes,size=(n_simulations,100),p=[0.004,0.996])
(installations_100.sum(axis=1) == 0).mean()

0.6586

In [ ]:
# - What is the probability that we observe an installation issue within 
# the first 150 students that download anaconda?
installations_150 = np.random.choice(corrupt_outcomes,size=(n_simulations,150),p=[0.004,0.996])
(installations_150.sum(axis=1) == 0).mean()

In [87]:
# - How likely is it that 450 students all download anaconda without an issue?
installations_450 = np.random.choice(corrupt_outcomes,size=(n_simulations,450),p=[0.004,0.996])
(installations_450.sum(axis=1) == 0).mean()

0.1679

In [ ]:
#7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

# - How likely is it that a food truck will show up sometime this week?

In [ ]:
#8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

# What if it's 20 people? 40?